// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyBanHang_Admin.Models;

#nullable disable

namespace QuanLyBanHang_Admin.Migrations
{
    [DbContext(typeof(QuanLyHangHoaContext))]
    [Migration("20251013100222_Chitietphieudathang")]
    partial class Chitietphieudathang
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("QuanLyBanHang_Admin.Models.Chitietphieudathang", b =>
                {
                    b.Property<string>("Mapdh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mapdh");

                    b.Property<string>("Mahang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mahang");

                    b.Property<double?>("Dongia")
                        .HasColumnType("float")
                        .HasColumnName("dongia");

                    b.Property<double?>("Soluong")
                        .HasColumnType("float")
                        .HasColumnName("soluong");

                    b.HasKey("Mapdh", "Mahang");

                    b.HasIndex("Mahang");

                    b.ToTable("chitietphieudathang", (string)null);
                });

            modelBuilder.Entity("QuanLyBanHang_Admin.Models.Chitietphieugiaohang", b =>
                {
                    b.Property<string>("Mapgh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mapgh");

                    b.Property<string>("Mahang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mahang");

                    b.Property<string>("Donvitinh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("donvitinh");

                    b.Property<double?>("Soluong")
                        .HasColumnType("float")
                        .HasColumnName("soluong");

                    b.HasKey("Mapgh", "Mahang");

                    b.HasIndex("Mahang");

                    b.ToTable("chitietphieugiaohang", (string)null);
                });

            modelBuilder.Entity("QuanLyBanHang_Admin.Models.Hanghoa", b =>
                {
                    b.Property<string>("Mahang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mahang");

                    b.Property<double?>("Dongia")
                        .HasColumnType("float")
                        .HasColumnName("dongia");

                    b.Property<string>("Donvitinh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("donvitinh");

                    b.Property<string>("Hinh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("hinh");

                    b.Property<string>("Maloai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("maloai");

                    b.Property<string>("Mansx")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mansx");

                    b.Property<string>("Tenhang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tenhang");

                    b.HasKey("Mahang");

                    b.HasIndex("Maloai");

                    b.HasIndex("Mansx");

                    b.ToTable("hanghoa", (string)null);
                });

            modelBuilder.Entity("QuanLyBanHang_Admin.Models.Khachhang", b =>
                {
                    b.Property<string>("Makh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("makh");

                    b.Property<string>("Diachi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("diachi");

                    b.Property<string>("Dienthoai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("dienthoai");

                    b.Property<int?>("Namsinh")
                        .HasColumnType("int")
                        .HasColumnName("namsinh");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("password");

                    b.Property<bool?>("Phai")
                        .HasColumnType("bit")
                        .HasColumnName("phai");

                    b.Property<string>("Tenkh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tenkh");

                    b.HasKey("Makh");

                    b.ToTable("khachhang", (string)null);
                });

            modelBuilder.Entity("QuanLyBanHang_Admin.Models.Loaihanghoa", b =>
                {
                    b.Property<string>("Maloai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("maloai");

                    b.Property<string>("Tenloai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tenloai");

                    b.HasKey("Maloai");

                    b.ToTable("loaihanghoa", (string)null);
                });

            modelBuilder.Entity("QuanLyBanHang_Admin.Models.Nhanvien", b =>
                {
                    b.Property<string>("Manv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("manv");

                    b.Property<string>("Diachi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("diachi");

                    b.Property<DateTime?>("Ngaysinh")
                        .HasColumnType("datetime")
                        .HasColumnName("ngaysinh");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("password");

                    b.Property<bool?>("Phai")
                        .HasColumnType("bit")
                        .HasColumnName("phai");

                    b.Property<string>("Tennv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tennv");

                    b.Property<byte?>("Vaitro")
                        .HasColumnType("tinyint")
                        .HasColumnName("vaitro");

                    b.HasKey("Manv");

                    b.ToTable("nhanvien", (string)null);
                });

            modelBuilder.Entity("QuanLyBanHang_Admin.Models.Nhasanxuat", b =>
                {
                    b.Property<string>("Mansx")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mansx");

                    b.Property<string>("Diachi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("diachi");

                    b.Property<string>("Tennsx")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tennsx");

                    b.HasKey("Mansx");

                    b.ToTable("nhasanxuat", (string)null);
                });

            modelBuilder.Entity("QuanLyBanHang_Admin.Models.Phieudathang", b =>
                {
                    b.Property<string>("Mapdh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mapdh");

                    b.Property<string>("Diachigh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("diachigh");

                    b.Property<string>("Makh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("makh");

                    b.Property<DateTime?>("Ngaydh")
                        .HasColumnType("datetime")
                        .HasColumnName("ngaydh");

                    b.Property<DateTime?>("Ngaygh")
                        .HasColumnType("datetime")
                        .HasColumnName("ngaygh");

                    b.HasKey("Mapdh");

                    b.HasIndex("Makh");

                    b.ToTable("phieudathang", (string)null);
                });

            modelBuilder.Entity("QuanLyBanHang_Admin.Models.Phieugiaohang", b =>
                {
                    b.Property<string>("Mapgh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mapgh");

                    b.Property<string>("Diachigh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("diachigh");

                    b.Property<string>("Manv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("manv");

                    b.Property<string>("Mapdh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mapdh");

                    b.Property<DateTime?>("Ngaygh")
                        .HasColumnType("datetime")
                        .HasColumnName("ngaygh");

                    b.Property<string>("Tennguoinhan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tennguoinhan");

                    b.HasKey("Mapgh");

                    b.HasIndex("Manv");

                    b.HasIndex("Mapdh");

                    b.ToTable("phieugiaohang", (string)null);
                });

            modelBuilder.Entity("QuanLyBanHang_Admin.Models.Chitietphieudathang", b =>
                {
                    b.HasOne("QuanLyBanHang_Admin.Models.Hanghoa", "MahangNavigation")
                        .WithMany("Chitietphieudathangs")
                        .HasForeignKey("Mahang")
                        .IsRequired()
                        .HasConstraintName("FK_chitietphieudathang_hanghoa");

                    b.HasOne("QuanLyBanHang_Admin.Models.Phieudathang", "MapdhNavigation")
                        .WithMany("Chitietphieudathangs")
                        .HasForeignKey("Mapdh")
                        .IsRequired()
                        .HasConstraintName("FK_chitietphieudathang_phieudathang");

                    b.Navigation("MahangNavigation");

                    b.Navigation("MapdhNavigation");
                });

            modelBuilder.Entity("QuanLyBanHang_Admin.Models.Chitietphieugiaohang", b =>
                {
                    b.HasOne("QuanLyBanHang_Admin.Models.Hanghoa", "MahangNavigation")
                        .WithMany("Chitietphieugiaohangs")
                        .HasForeignKey("Mahang")
                        .IsRequired()
                        .HasConstraintName("FK_chitietphieugiaohang_hanghoa");

                    b.HasOne("QuanLyBanHang_Admin.Models.Phieugiaohang", "MapghNavigation")
                        .WithMany("Chitietphieugiaohangs")
                        .HasForeignKey("Mapgh")
                        .IsRequired()
                        .HasConstraintName("FK_chitietphieugiaohang_phieugiaohang");

                    b.Navigation("MahangNavigation");

                    b.Navigation("MapghNavigation");
                });

            modelBuilder.Entity("QuanLyBanHang_Admin.Models.Hanghoa", b =>
                {
                    b.HasOne("QuanLyBanHang_Admin.Models.Loaihanghoa", "MaloaiNavigation")
                        .WithMany("Hanghoas")
                        .HasForeignKey("Maloai")
                        .HasConstraintName("FK_hanghoa_loaihanghoa");

                    b.HasOne("QuanLyBanHang_Admin.Models.Nhasanxuat", "MansxNavigation")
                        .WithMany("Hanghoas")
                        .HasForeignKey("Mansx")
                        .HasConstraintName("FK_hanghoa_nhasanxuat");

                    b.Navigation("MaloaiNavigation");

                    b.Navigation("MansxNavigation");
                });

            modelBuilder.Entity("QuanLyBanHang_Admin.Models.Phieudathang", b =>
                {
                    b.HasOne("QuanLyBanHang_Admin.Models.Khachhang", "MakhNavigation")
                        .WithMany("Phieudathangs")
                        .HasForeignKey("Makh")
                        .HasConstraintName("FK_phieudathang_khachhang");

                    b.Navigation("MakhNavigation");
                });

            modelBuilder.Entity("QuanLyBanHang_Admin.Models.Phieugiaohang", b =>
                {
                    b.HasOne("QuanLyBanHang_Admin.Models.Nhanvien", "ManvNavigation")
                        .WithMany("Phieugiaohangs")
                        .HasForeignKey("Manv")
                        .HasConstraintName("FK_phieugiaohang_nhanvien");

                    b.HasOne("QuanLyBanHang_Admin.Models.Phieudathang", "MapdhNavigation")
                        .WithMany("Phieugiaohangs")
                        .HasForeignKey("Mapdh")
                        .HasConstraintName("FK_phieugiaohang_phieudathang");

                    b.Navigation("ManvNavigation");

                    b.Navigation("MapdhNavigation");
                });

            modelBuilder.Entity("QuanLyBanHang_Admin.Models.Hanghoa", b =>
                {
                    b.Navigation("Chitietphieudathangs");

                    b.Navigation("Chitietphieugiaohangs");
                });

            modelBuilder.Entity("QuanLyBanHang_Admin.Models.Khachhang", b =>
                {
                    b.Navigation("Phieudathangs");
                });

            modelBuilder.Entity("QuanLyBanHang_Admin.Models.Loaihanghoa", b =>
                {
                    b.Navigation("Hanghoas");
                });

            modelBuilder.Entity("QuanLyBanHang_Admin.Models.Nhanvien", b =>
                {
                    b.Navigation("Phieugiaohangs");
                });

            modelBuilder.Entity("QuanLyBanHang_Admin.Models.Nhasanxuat", b =>
                {
                    b.Navigation("Hanghoas");
                });

            modelBuilder.Entity("QuanLyBanHang_Admin.Models.Phieudathang", b =>
                {
                    b.Navigation("Chitietphieudathangs");

                    b.Navigation("Phieugiaohangs");
                });

            modelBuilder.Entity("QuanLyBanHang_Admin.Models.Phieugiaohang", b =>
                {
                    b.Navigation("Chitietphieugiaohangs");
                });
#pragma warning restore 612, 618
        }
    }
}
